### ISSUE TITLE
Cyther Issues on OS X El Capitan

### ISSUE THREAD

**Issue by runeimp** [nickpandolfi/Cyther#3]
I installed Cyther via 
```
$ pip3 install Cyther
Collecting Cyther
  Using cached Cyther-0.7.0-py3-none-any.whl
Installing collected packages: Cyther
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/cyther'
```

I'm not sure why this was happening. To get around it I needed to `pip3 uninstall Cyther` and add the `/usr/local/cyther` directory myself. I believe this would be fixed if it would simply ask for `sudo` permission when trying to create the directory in that path if necessary. I've had no problems with Homebrew installing apps or with `pip` or `pip3` for the other few packages I've tried. I have no idea if this is actually a `pip` problem or just a package configuration issue but wanted to bring it to your attention. After creating the directory and giving it the same permissions as the rest of the directories in that path I got:

```
$ pip3 install Cyther
Collecting Cyther
  Using cached Cyther-0.7.0-py3-none-any.whl
Installing collected packages: Cyther
Successfully installed Cyther-0.7.0
```

So I expect it was installed properly at that point. Then had the problem that I couldn't find the `cytherize` executable. I eventually found `/usr/local/bin/cytherize.py` but it was not marked executable nor setup as an executable script with a bangpath. None of the docs show using this script that is not executable but located in an executables path location. At least not that I came across. Please excuse me if I sound critical as that is not my intention. I'm new to Python this is only the third or forth item I've installed via `pip3` after getting into Python development. I'm just trying to be as plain and clear as possible.  O:-)

So I tried the following and got the shown errors:
```
$ python3 /usr/local/bin/cytherize.py input.py
Traceback (most recent call last):
  File "/usr/local/bin/cytherize.py", line 1, in <module>
    from cyther import runAsScript
  File "/usr/local/lib/python3.6/site-packages/cyther/__init__.py", line 3, in <module>
    from .cyther import *
  File "/usr/local/lib/python3.6/site-packages/cyther/cyther.py", line 164, in <module>
    L_OPTION = '-l' + sift(RUNTIME_DIRS)
  File "/usr/local/lib/python3.6/site-packages/cyther/cyther.py", line 57, in sift
    result = max(list(s), key=len)
ValueError: max() arg is an empty sequence
```

This happens even if I have nothing in the script but `print("Hello, world!")`. Am I running this incorrectly? I thought it would be the closest equivalent of `$ cytherize example_file.py` suggested in the docs on PyPI and your GitHub page.

**Comment by mbdevpl** [comment]
I submitted the issue of cytherize being not executable earlier as #1 and it was resolved, the current way to call cyther seems to be through `cyther` command, not `cytherize.py`. The new version (0.8), however, seems to not be released yet on PyPI. The PyPI version is outdated (from April 2016). Did you try cloning Cyther repo, building it yourself and installing that?

Rough sequence of commands to do the above:
```
git clone https://github.com/nickpandolfi/Cyther
cd Cyther
python3 setup.py bdist_wheel
pip install dist/*.whl
```

**Comment by nickpandolfi** [comment]
Yes the new executable will be in version 0.8 which is still under development (Many bug fixes are being made). This repository does not reflect any changes made to the pypi code. Sorry its taking so long I'm a busy dude. Also theres going to be a complete API change. I figured might as well optimize the access to cyther while its not being used yet.

**Comment by nickpandolfi** [comment]
And thank you very much runeimp! Ill have to take a look at that!

**Comment by nickpandolfi** [comment]
When I pushed 0.7 to pypi in April, it was working on linux and on windows at least for me. Now when I test 0.7 directly from pypi, it doesnt work for me anymore, giving me various errors. So here is my methodology on development as of now:

1) Create low level tools and utilities Cyther needs
2) Fix any known bugs with tools
3) Disable old, not working functionality
4) Reimplement the functionality with new tools

Then the last thing would be to actually get it working for the user. Cyther as in the repository right now, is guaranteed to NOT work, as I have disabled all outside functionality for a bit. Im working from the ground up.
